// client-angular/src/pages/books/books.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router, RouterModule, RouterOutlet } from '@angular/router';
import { BooksService } from '../../core/data-services/books.service';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faEdit, faTrash, faPowerOff  } from '@fortawesome/free-solid-svg-icons'; 
import { AuthenticationService } from '../../core/data-services/authentication.service';

@Component({
  selector: 'app-books',
  standalone: true,
  imports: [RouterOutlet, CommonModule, RouterModule, FontAwesomeModule], 
  templateUrl: './books.component.html',
  styleUrls: ['./books.component.css']
})
export class BooksComponent implements OnInit {
  userName: string = '';
  booksList: any[] = []; 
  page: number = 1;
  pageSize: number = 5;
  faEdit = faEdit;
  faTrash = faTrash;
  faPowerOff = faPowerOff;

  constructor(private router: Router, private bookService: BooksService, private authService: AuthenticationService) { 
    this.userName = authService.getFullName() ?? '';
  }

  ngOnInit() {
    this.fetchMoreBooks();
  }

  editBook(bookId: number) {
    // Lógica para editar livro
    this.router.navigate([`/book/new/${bookId}`]);
  }

  deleteBook(bookId: number) {
    // Lógica para deletar livro
    console.log(`Deleting book with id: ${bookId}`);
    this.booksList = this.booksList.filter(book => book.id !== bookId);
  }

  fetchMoreBooks() {
    this.bookService.fetchMoreBooks(this.page, this.pageSize).subscribe({
      next: (response) => {
        this.booksList = [...this.booksList, ...response.list];
        this.page += 1;
      },
      error: (error) => {
        if (error.status !== 401)
          alert('Fetch failed: Try again!');
      }
    });
  }

  logout() {
    this.authService.clearUserData();
    this.router.navigate(['/']);  // Redireciona para a página de login
  }

}

<div class="book-container">
  <header>
    <img src="logo.svg" alt="Book store" />
    <span>Welcome, <strong>{{ userName.toUpperCase() }}</strong>!</span>
    <a class="button" [routerLink]="['/book/new/0']">Add new book</a>
    <button type="button" (click)="logout()">
      <fa-icon [icon]="faPowerOff" size="lg" [style.color]="'#251FC5'"></fa-icon>
    </button>
    
  </header>

  <h1>Registered Books</h1>

  <ul>
    <li *ngFor="let book of booksList">
      <strong>Title:</strong>
      <p>{{ book.title }}</p>

      <strong>Author:</strong>
      <p>{{ book.author }}</p>

      <strong>Price:</strong>
      <p>{{ book.price | currency: 'USD':'symbol' }}</p>

      <strong>Release Date:</strong>
      <p>{{ book.launchDate | date: 'longDate' }}</p>

      <button type="button" (click)="editBook(book.id)">
        <fa-icon [icon]="faEdit" size="1x" [style.color]="'#251FC5'"></fa-icon>
      </button>
  
      <button type="button" (click)="deleteBook(book.id)">
        <fa-icon [icon]="faTrash" size="1x" [style.color]="'#251FC5'"></fa-icon>
      </button>
    </li>
  </ul>

  <button class="button" (click)="fetchMoreBooks()" type="button">Load more</button>
</div>

// client-react/src/pages/Books/index.js
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from "react-router-dom";
import { FiPower, FiEdit, FiTrash2 } from "react-icons/fi";
import api from '../../services/api';

import "./styles.css";
import logoImage from '../../assets/logo.svg'

export default function Book(){
    const [booksList, setBooksList] = useState([]);
    const [page, setPage] = useState(1);

    const userName = localStorage.getItem('userName');    
    const navigate = useNavigate();

    const accessToken = localStorage.getItem("accessToken");
    const authorization = { headers: { Authorization: `Bearer ${accessToken}`}};

    useEffect(() => { 
        try {
            fetchMoreBooks();
        } catch (error) {
            alert('Creation failed: Try again!');
        } 
     }, [accessToken])


     async function fetchMoreBooks(){
        const response = await api.get(`api/books/asc/5/${page}`, authorization);
        setBooksList([...booksList, ... response.data.list]);
        setPage(page + 1);        
     }

    async function deleteBook(id) {
        try {
            await api.delete(`api/books/${id}`, authorization);
            setBooksList(booksList.filter(book => book.id !== id));    
        } catch (error) {
            alert('Delete failed: Try again!');
        }
    }
    
    async function logout() {
        try {
            await api.get('api/auth/revoke', authorization);

            localStorage.clear();
            navigate('/');
        } catch (error) {
            alert('Logout failed: Try again!');
        }
    }
    

    async function editBook(id){
        try {
            navigate(`/book/new/${id}`);
        } catch (error) {
            alert('Edit book failed: Try again!');
        }
    }

    return(
        <div className="book-container">
            <header>
                <img src={logoImage} alt="Book store"/>
                <span>Welcome, <strong>{userName.toUpperCase()}</strong>!</span>
                <Link className="button" to="/book/new/0">Add new book</Link>
                <button type="button">
                    <FiPower size={18} color="251FC5" onClick={logout} />
                </button>
            </header>
            <h1>Registered Books</h1>
            <ul>
                {booksList.map(book => (
                    <li key={book.id}>
                        <strong>Title:</strong>
                        <p>{book.title}</p>
                        <strong>Author:</strong>
                        <p>{book.author}</p>
                        <strong>Price</strong>
                        <p>{Intl.NumberFormat('en-us', {style: 'currency', currency: 'USD'}).format(book.price)}</p>
                        <strong>Release Date</strong>
                        <p>{Intl.DateTimeFormat('en-US').format(new Date(book.launchDate))}</p>

                        <button type="button" onClick={() => editBook(book.id) }>
                            <FiEdit size={20} color="251FC5"/>
                        </button>
                        <button onClick={() => deleteBook(book.id)} type="button">
                            <FiTrash2 size={20} color="251FC5"/>
                        </button>
                    </li>
                ))}                                
            </ul>
            <button className='button' onClick={fetchMoreBooks} type='button'>Load more</button>
        </div>
    );
}
