// client-angular/src/pages/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthenticationService } from '../../core/data-services/authentication.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  
  constructor(private authService: AuthenticationService,  private router: Router) { }

  ngOnInit() { }

  async login(event: Event){
    event.preventDefault();

    const form = new FormData((event.target as HTMLFormElement));

    const userName = form.get('userName') as string;
    const password = form.get('password') as string;

    this.authService.signin(userName, password).subscribe({
      next: (response) => {
        this.authService.storeUserData(userName, response);
        this.router.navigate(['/books']);
      },
      error: (error) => {
        alert(`Error: ${error.message}`);
      }
    });
  } 
}


<div class="login-container">
  <section class="form">
      <img src="logo.svg" alt="logo" />
      <form class="form" (submit)="login($event)">
          <h1>Access your Account</h1>
          <input placeholder="Username" name="userName" />
          <input type="password" placeholder="Password" name="password" />
          <button class="button" type="submit">Login</button>
      </form>
  </section>
  <img src="padlock.png" alt="login" />
</div>

// client-react/src/pages/Login/index.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';

import "./styles.css";
import logoImage from '../../assets/logo.svg'
import padlock from '../../assets/padlock.png'

export default function Login(){
    const [userName, setUserName] = useState('');
    const [password, setPassword] = useState('');
    const navigate = useNavigate();

    async function login(e){
        e.preventDefault();
        const data = {
            userName, 
            password
        };
        try{
            const response = await api.post('api/auth/signin', data);

            localStorage.setItem('userName', userName);
            localStorage.setItem('accessToken', response.data.accessToken);
            localStorage.setItem('refreshToken', response.data.refreshToken);
            
            navigate('/books');

        }catch(error) {
            alert('Login failed: Try again')
        }
    }

    return (
        <div className='login-container'>
            <section className='form'>
                <img src={logoImage} alt='logo' />
                <form className='form' onSubmit={login}>
                    <h1>Access your Account</h1>
                    
                    <input placeholder='Username' value={userName} onChange={e => setUserName(e.target.value)}/>
                    <input type='password' placeholder='Password' value={password} onChange={e => setPassword(e.target.value)}/>
                    <button className='button' type='submit'>Login</button>
                </form>
            </section>
            <img src={padlock} alt='login' />
        </div>
    );
};
